default:
  image: gitlab.uk.cambridgeconsultants.com:5000/p5851/highway_docker_image:main

build_x86:
  stage: build
  script:
    - echo "Building for x86..."
    - mkdir -p build_x86 && cd build_x86
    - CC=gcc-12 CXX=g++-12 cmake .. -DHWY_WARNINGS_ARE_ERRORS:BOOL=ON -DCMAKE_BUILD_TYPE=Release
    - make -j
    - cd ..
  artifacts:
    paths:
      - build_x86/

build_arm8:
  stage: build
  script:
    - echo "Building for ARMv8..."
    - mkdir build_arm8 && cd build_arm8
    - export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
    - CC=aarch64-linux-gnu-gcc-12 CXX=aarch64-linux-gnu-g++-12 cmake .. -DHWY_WARNINGS_ARE_ERRORS:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CROSSCOMPILING_EMULATOR=/usr/bin/qemu-aarch64
    - make -j
    - cd ..
  artifacts:
    paths:
      - build_arm8/

test_x86:
  stage: test
  dependencies:
    - build_x86
  script:
    - cd build_x86
    - echo "Running x86 tests..."
    - ctest -j --output-on-failure

test_arm8:
  stage: test
  dependencies:
    - build_arm8
  script:
    - export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
    - cd build_arm8
    - echo "Running ARMv8 tests..."
    - ctest -j --output-on-failure
